spring:
  application:
    name: point-demo
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  #    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    hikari:
#      jdbc-url: jdbc:h2:mem:point
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:
      jdbc-url: jdbc:mysql://localhost:3306/db_point
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123
#  h2:
#    console:
#      enabled: true
logging:
  level:
    root: debug
